title: Каскадная генерация

description: >
  С версии 1.11.2, модеры столкнулись с проблемой "каскадной генерации". Что это, чем опасно и как избежать?

contributors:
  -
    name: CMTV
    role: Перенес с форума
    github: https://github.com/CMTV
