title: Установка программ

description: >
  Установка необходимых программ, которые необходимы для разработки BungeeCord плагинов.

contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/Ivasik78
