title: Создание своего инвентаря

description: >
  Создание отдельного инвентаря со своими слотами, который можно открыть по нажатию кнопки "H". Добавим возможность менять кнопку.

contributors:
  -
    name: CMTV
    role: Перенес с форума
    github: https://github.com/CMTV
