# Title
title: Система временных эффектов

# Description (~160 symbols)
description: >
  В данном туториале описан процесс создания собственной системы временных эффектов (баффов), которая будет работать со всеми существами(наследниками EntityLivingBase). Работают они так же, как и ванильные эффекты зелий, однако имеют ряд улучшений и оптимизаций.

# Contributors
contributors:
  -
    name: CMTV
    role: Перенес с форума
    github: https://github.com/CMTV
