title: Интеграция с Just Enough Items

description: >
  Реализация поддержки Just Enough Items (JEI) для своего мода с наглядными примерами.

contributors:
  -
    name: CMTV
    role: Перенес с форума
    github: https://github.com/CMTV
