title: Предмет с временем горения

description: >
  Создание своего предмета, который может использоваться в печке

contributors:
  -
    name: CMTV
    role: Перес с форума
    github: https://github.com/CMTV
