title: Главный класс

description: >
  Основной класс в котором будет происходить регистрация команд, событий и т.д.

contributors:
  -
    name: Ivasik
    role: Автор
    github: https://github.com/Ivasik78
